import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { gql } from '@apollo/client'
import client from '../apollo/client'
import styles from '../styles/Home.module.css'
import { IPet } from '../types'

type Props = {
  pets: Array<IPet>
}

const Home: NextPage<Props> = ({ pets }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {pets.map(pet => (
            <li key={pet.id}>
              {pet.name}
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async() => {
  const { data } = await client.query({
    query: gql`
      query getPets {
        pets(filters: {petTypeId: 1}) {
          id
          name
          status
          pictureDefault {
            url
            
          }
          breed {
            name
          }
          creator {
            firstname
            lastname
          }
        }
      }
    `,
  });

  return {
    props: {
      pets: data.pets
    },
    revalidate: 20
 };
}