import type { GetServerSideProps, GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import PetList from '../components/PetList';
import client from '../apollo/client';
import { GET_PETS } from '../apollo/queries';
import { PetListProps } from '../types';
import Banner from '../components/Banner';
import MainSearch from '../components/MainSearch';
import { useEffect } from 'react';

const Home: NextPage<PetListProps> = ({pets}) => {

  useEffect(()=>{
    const fetchData = async () => {
      const res = await fetch('/api/jwt');
      const json = await res.json();
      console.log(json?.accessToken);
    };
    fetchData();
  },[]);

  return (
    <div>
      <Head>
        <title>Pets Adoption</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <MainSearch />
      <PetList pets={pets}/>
    </div>
  );
};

export default Home;


export const getStaticProps: GetStaticProps = async() => {
  const { data } = await client.query({query: GET_PETS, variables: {limit: 5, petTypeId: null}});

  return {
    props: {
      pets: data.pets
    }
    // revalidate: 20
 };
};